### PR TITLE
Add font-sriracha

### PR DESCRIPTION
**Pull request by lread**
Google font: https://fonts.google.com/specimen/Sriracha
Open Font License: https://github.com/cadsondemak/sriracha/blob/master/OFL.txt

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
        _Name is included, referencing latest version via github._
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-fonts/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> + The Cask is too obscure. Examples:
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

**Comment by lread** [comment]
Thanks for the review @vitorgalvao, I do appreciate you spending the time.

I guess I thought it being listed on Google Fonts would be sufficient, do you have a minimum number of views that you use to determine notability?  I [currently see](https://fonts.google.com/analytics) a total of 505,969,227 total views and 6,618,376 views in the last seven days.

**Comment by vitorgalvao** [comment]
Views don’t indicate a desire to install the font, which is what we do. Our notability requirements aren’t perfect.

**Comment by lread** [comment]
Ok, thanks for the follow-up @vitorgalvao, I sincerely appreciate your time.

I'm guessing that a low github star count might not necessarily correlate to a font's popularity (or lack thereof), but high a star count would be a good indicator of popularity. I see the challenge.  Not simple.

Anyhow, thanks!

**Pull request closed without merging**
