### PR TITLE
font-noto-serif-cjk 2.002

### PR DESCRIPTION
**Pull request by muzimuzhi**
**Why need an update**

The old url https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJK.ttc.zip provides an outdated version 1.001, packed back in 2017. While the latest version is 2.002, see https://github.com/notofonts/noto-cjk/releases/tag/Serif2.002.

**Why updated in this way**

https://fonts.google.com only provides variable ttf font file in Noto Serif CJK bundle for each language, for example `NotoSerifSC[wght].ttf` and its corresponding cask [`font-noto-serif-sc.rb`](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-noto-serif-sc.rb) for Noto Serif CJK SC (Simplified Chinese). But this cask provides a static super ttc font file, which is only available from releases of repository https://github.com/notofonts/noto-cjk.

**Remark**

More casks need to be updated in this way, including symmetric Noto Sans CJK cask [`font-noto-sans-cjk.rb`](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-noto-sans-cjk.rb) and language specific Serif and Sans casks like [`font-noto-sans-cjk-sc.rb`](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-noto-sans-cjk-sc.rb).

I started with only one cask to check I did everything right.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Is there a reason for requiring the static fonts over the variable font as distributed by Google Fonts?
Also, is there a reason for continuing with the `ttc` over our preferred `otf`?

**Comment by muzimuzhi** [comment]
> Is there a reason for requiring the static fonts over the variable font as distributed by Google Fonts?

Not all softwares can deal with variable fonts, so static ones are still in demand.

> Also, is there a reason for continuing with the `ttc` file over our preferred `otf`?

I just followed what was provided by this cask, which was a single `NotoSerifCJK.ttc`.

**Comment by muzimuzhi** [comment]
From [`notofonts/noto-cjk` repository](https://github.com/notofonts/noto-cjk/tree/main/Serif#super-otc),

> ## Super OTC
> [...] This format is the easiest to install of all the formats and takes the least space for static fonts due to sharing between the 35 parts.
> 
> Select this deployment format if you want all five languages and all seven weights in a single and easy-to-manage font resource that includes 35 fonts. [...]
>
> ## Static OTCs
> Select this deployment format if you want all five languages and particular weights, or if your environment does not support the Super OTC. [...]

And from Adobe's famous [download guide](https://github.com/adobe-fonts/source-han-serif/blob/release/download-guide-source-han.pdf) for corresponding font Source Han Sans/Serif, Super OTC seems recommended for macOS users.
image

**Review by bevanjkay — APPROVED** [review]

**Comment by muzimuzhi** [comment]
@bevanjkay Can I ask what's the difference between `:stable` and `:url`? I didn't find their definition in https://docs.brew.sh/Brew-Livecheck, or maybe just because I don't speak Ruby.

**Comment by muzimuzhi** [comment]
Thanks. Another question, to bump casks for `font-noto-serif-cjk-<lang>.rb` their `sans` siblings, I'd like to know is it allowed to update several casks in a single PR?

**Comment by bevanjkay** [comment]
Generally we don't allow it, but as these are all related changes it's ok this time.

**Comment by muzimuzhi** [comment]
I decided to do all the bumps in several PRs:
- #8720, the current one
- #8721, bump `font-noto-serif-cjk-(jk|kr|sc|tc)` casks 
- add `font-noto-serif-cjk-hk` cask
- bump `font-noto-sans-cjk` and four existing language specific casks to [2.004](https://github.com/notofonts/noto-cjk/releases/tag/Sans2.004)
- add `font-noto-sans-cjk-hk` cask

**Pull request merged**
