### PR TITLE
Update font-fira-mono-nerd-font from 2.1.0 to 2.2.1

### PR DESCRIPTION
**Pull request by b-reich**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by reitermarkus — DISMISSED** [review]

**Comment by Finii** [comment]
@b-reich Is there any reason this updates to `2.2.1` and not `2.2.2` ?

Livecheck ignored?

image

**Comment by Finii** [comment]
This package is broken (which is unrelated to this PR), btw, see https://github.com/ryanoasis/nerd-fonts/issues/1003

Nerd Fonts has a cask-updater-script, maybe I should repair and activate it? Do you have an opinion on that, @b-reich ?

**Comment by Finii** [comment]
Something is strange with the CI setup @miccal.

Why does the bot merge this PR, albeit the tests failed?

image

**Comment by b-reich** [comment]
> This package is broken (which is unrelated to this PR), btw, see [ryanoasis/nerd-fonts#1003](https://github.com/ryanoasis/nerd-fonts/issues/1003)
> 
> Nerd Fonts has a cask-updater-script, maybe I should repair and activate it? Do you have an opinion on that, @b-reich ?

You are right..
Was a mistake

@Finii love to see this working again. Updating manualy all the fonts is a bit annoying. I wrote a litte helper script. But this is not a proper solution.

**Comment by Finii** [comment]
Roger, will try to set some automatic PR creation up over at Nerd Fonts' CI.
Will ping you as CI expert (read your profile page) afterwards \*frech grins\*

**Pull request closed without merging**
