### PR TITLE
add font-recursive-code

### PR DESCRIPTION
**Pull request by patrickfatrick**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-fonts/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you. They mention on the repo that this will be coming to Google Fonts, so I’d rather wait for that. We have a script that will catch it when that happens and will make it significantly easier to maintain.

**Comment by patrickfatrick** [comment]
Thanks for fixing that left-over version number! Regarding Google Fonts it's already there (https://fonts.google.com/specimen/Recursive) and in fact the google font is already a cask (https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-recursive.rb). But the Google Font does not include the coding variant and I'm not sure there's a plan to add it there. This is my first cask PR so I'm not sure how it works but can we update the url later if the coding-specific variant is added to Google Fonts?

**Comment by vitorgalvao** [comment]
> and I'm not sure there's a plan to add it there.

Then that should be confirmed first.

> can we update the url later if the coding-specific variant is added to Google Fonts?

Technically yes. In practice, experience tells me the most probable outcome is it will be forgotten and left indefinitely on the old URL. The main one isn’t that popular:

```
font-recursive
30 days: 18 (#1991)
90 days: 54 (#1883)
365 days: 111 (#2998)
Age: 165 days (added 2020, June 14)
```

If we were having this conversation on the main tap, I might default to include, but on the fonts repo I’d rather be a bit more conservative because it’s already somewhat messy.

**Comment by patrickfatrick** [comment]
You got it, will confirm with the font creator what his plans are re: google fonts.

**Comment by patrickfatrick** [comment]
@vitorgalvao Confirmed that there are no real plans to add this particular variant to Google Fonts, via https://github.com/arrowtype/recursive/issues/422

**Comment by vitorgalvao** [comment]
> Potentially, Google Fonts would add Recursive Code someday if there were demand for it. The typical way to get this started would be to file an issue requesting it at [google/fonts](https://github.com/google/fonts).

That’s the way to go, then. If there’s no real demand for it, there’s no point in us adding it here as well.

**Comment by patrickfatrick** [comment]
> there’s no point in us adding it here as well

Yes, there is. As I said Google Fonts already has recursive, and the author of the font seemingly doesn't know what a Google Font for the "Code" variants would look like. I think this is because Google Fonts is intended for consumption by websites, so I don't think it makes sense to add a different recursive set to Google Fonts for what is essentially a preconfigured set of options of the existing font, plus powerline symbols.

Homebrew Casks are intended for easy consumption of fonts by programmers so I think it _does_ make sense for this platform. Meanwhile there are several popular programming fonts that are not on Google Fonts. eg: iosevka, fantasque sans mono, jetbrains mono, cascadia code, mononoki, monoid, dejavu, hack, terminus, go mono. There are neither any [nerd fonts](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts) on Google, nor any [powerline fonts](https://github.com/powerline/fonts).

**Review by vitorgalvao — DISMISSED** [review]

**Review by miccal — APPROVED** [review]

**Comment by patrickfatrick** [comment]
Thanks for merging!

**Pull request merged**
