### PR TITLE
Add font-elstob 1.003

### PR DESCRIPTION
**Pull request by adunning**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-fonts/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by adunning** [comment]
The downloaded archive provides variable-width fonts, OTF, and TTF. This installs only the first, with a separate version available in #2078 to provide compatibility with applications that do not support these. Let me know if you think there's a better way to go about this.

**Comment by vitorgalvao** [comment]
We should be installing the `desktop` fonts, not the `web` fonts, so going with those.

Thank you for being proactive and doing both PRs.

**Comment by adunning** [comment]
It's a slightly weird approach to packaging. Along with versions intended for 'web' use, the package also includes variable fonts (what I have included here) that seem to be identical to the desktop fonts, and function more cleanly within macOS applications that use system font support. The 'desktop' versions are only necessary for LaTeX and some older applications that do not support OpenType variable fonts. I've therefore installed both, but would be interested to know if I am misunderstanding.

**Comment by vitorgalvao** [comment]
I’m unsure here. I haven’t been keeping up with variable font tech, so I’m not sure how ready or not they are. Might be worth opening an issue in the main repo to discuss which to include.

We’re not going to provide both, the question is “should we start defaulting to variable fonts, or is it too soon?”

**Comment by adunning** [comment]
I've done more research into this with #2101 – given that there are several other fonts doing something similar, I feel it would be useful to include both Elstob and ElstobD (on the model of the Source families and others). Alternatively, if you think such duplication is unacceptable, I think that only this variable version should be provided.

**Comment by vitorgalvao** [comment]
> Alternatively, if you think such duplication is unacceptable, I think that only this variable version should be provided.

Let’s do that. Fonts aren’t popular enough to justify duplication. Thank you for your continued effort on this repo.

**Pull request closed without merging**
