### PR TITLE
add/update all Google Fonts, take II

### PR DESCRIPTION
**Pull request by afeld**
Follow-up to https://github.com/Homebrew/homebrew-cask-fonts/pull/2095, with the requested changes. Squashed most of the commits for readability. Since the diff is so huge, here is the link to [the script](https://github.com/afeld/homebrew-cask-fonts/blob/google-fonts-B/developer/bin/import_google_fonts) and [the template](https://github.com/afeld/homebrew-cask-fonts/blob/google-fonts-B/developer/cask.rb.j2) by themselves.

This pull request adds 548 Google font casks, deletes five missing ones, and fixes dozens of others.

---

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-fonts/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by afeld** [comment]
Seems the Travis failure is a timeout; not sure if there's anything I can do about that.

**Comment by vitorgalvao** [comment]
Fantastic! Thank you.

I’ll merge and move the developer script to the main repo, so don’t be alarmed if you see it missing from here.

**Comment by vitorgalvao** [comment]
I forgot we already had another deve script here, perhaps they should both stay, I’ll have a think about it.

Question: would it be possible to include the template in the script itself? We prefer those to be self-contained.

**Comment by driesvints** [comment]
Why was `font-roboto-condensed` removed?

**Comment by afeld** [comment]
It's now a variable font (`Roboto`) where `Condensed` is one of the available weights.

https://github.com/Homebrew/homebrew-cask-fonts/blob/a904d41bb60af7810273aea7cf9140dc883fffb8/Casks/font-roboto.rb#L15

**Comment by driesvints** [comment]
@afeld thanks!

**Pull request merged**
