### PR TITLE
font-aurulent-nerd-font: remove duplicate

### PR DESCRIPTION
**Pull request by bevanjkay**
Removing duplication of `font-aurulent-sans-mono-nerd-font ==> font-aurulent-nerd-font` as the latter is handled by upstream's release CI run.
The token is potentially slightly incorrect, however the entire repo is handled automatically, much like Google Fonts.
Also added to `cask_renames.json`.

cc: @Finii

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for the information. I guess the short(er) cask name is my error.

It started as `font-aurulentsansmono-nerd-font.rb`, named by us (Nerd Font) (https://github.com/Homebrew/homebrew-cask-fonts/commit/ecdf756a629ef0293da396fdccb60919ec2de135)

Then it has been dash-i-fied `font-aurulent-sans-mono-nerd-font.rb`(https://github.com/Homebrew/homebrew-cask-fonts/commit/e8c2732486e9b403397fc7508ceb6cb105632455)

Then just one year ago the Nerd Font release CI got an overhaul and I (personally) put in `font-aurulent-nerd-font.rb`, despite the fact that I did look up all cask names and put them into a 'database' in our CI (see commit message below).

So I broke it. Sorry :unamused: 

Do you @bevanjkay have any suggestion? Should I change the cask name for our CI generator to include `sans-mono`, and you sunset the other name via 'rename'? i.e.
* Nerd Font creates now `font-aurulent-sans-mono-nerd-font.rb`
* You put a rename notice on `font-aurulent-nerd-font.rb`

----

Here our CI commit that introduced the breaking change:
https://github.com/ryanoasis/nerd-fonts/commit/c8cb5c78a7f68f91359c649dc1bca95bc59debcd

```
commit c8cb5c78a7f68f91359c649dc1bca95bc59debcd
Author: Fini Jastrow <ulf.fini.jastrow@desy.de>
Date:   Sat Nov 26 18:00:17 2022 +0100

    casks: Hardcode cask names in fonts.json
    
    [why]
    We want to replace the existing casks. But they do not have a consistent
    way to name the casks. Sometimes blanks are preserved (as dashes):
    
          "unpatchedName": "DejaVu Sans Mono",
          "patchedName": "DejaVuSansMono",
          "caskName": "dejavu-sans-mono",
    
    The above looks like cask-name == unpatched-name.
    
    Here they introduce blanks out of thin air (the original name does not
    have blanks):
    
          "unpatchedName": "DaddyTimeMono",
          "patchedName": "DaddyTimeMono",
          "caskName": "daddy-time-mono",
    
    Here they add something to the name??!:
    
          "unpatchedName": "Gohu",
          "patchedName": "Gohu",
          "caskName": "gohufont",
    
    Here the cask-name follows the RFN renaming:
    
          "unpatchedName": "Hasklig",
          "patchedName": "Hasklug",
          "caskName": "hasklug",
    
    Here they do not follow the RFN renaming:
    
          "unpatchedName": "Liberation",
          "patchedName": "LiterationMono",
          "caskName": "liberation",
    
    And there are a lot more ... strangenesses.
    I guess the casks have been created by different people following
    different ideas.
    
    [how]
    All these inconsistencies makes setting up rules how to determine the
    cask name from the other names very complicated and brittle.
    
    If we want to preserve the existing cask names the simplest and most
    stable approach is to explicitely specify them in the fonts.json
    database:
    Introduce a new data field "caskName", like shown above.
    
    Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>
```

**Comment by bevanjkay** [comment]
@Finii Yes, let's do this the other way around.

So we will rename `font-aurulent-nerd-font ==> font-aurulent-sans-mono-nerd-font`

**Comment by Finii** [comment]
Thanks for the quick reply :-)

I'll change our CI then. Sorry for all the trouble. Thanks for fixing :green_heart:

**Comment by Finii** [comment]
Resolved on our side via

https://github.com/ryanoasis/nerd-fonts/commit/701233bf3bb6515ea9004794e9a2a3e6678fda42

**Comment by bevanjkay** [comment]
I have flipped the rename following the above conversation.

**Review by miccal — APPROVED** [review]

**Pull request merged**
