### PR TITLE
Fix `font-noto-sans`

### PR DESCRIPTION
**Pull request by wenkokke**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

---

This PR fixes issue #9060.

### CODE REVIEW

**Comment by bevanjkay** [comment]
If the variable font files can be installed alongside the static files then they should be retained.

**Comment by wenkokke** [comment]
So it should be both the original font statements and the ones I added?

**Comment by p-linnane** [comment]
@wenkokke Please address @bevanjkay's feedback so we can gets this merged. Otherwise it will be closed. Thanks.

**Review by p-linnane — APPROVED** [review]

**Comment by p-linnane** [comment]
Thanks @wenkokke!

**Pull request merged**
