### PR TITLE
Update FiraCode Nerd Font

### PR DESCRIPTION
**Pull request by julienma**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-fonts/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by julienma** [comment]
This update downloads the [font files directly](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode), instead of the repo release which is [way outdated](https://github.com/ryanoasis/nerd-fonts/releases).

This fixes 2 issues:
- use latest version of the font (`1.206` -> `2.0`), cf. https://github.com/ryanoasis/nerd-fonts/issues/424
- use real font name (`Fura` -> `Fira`), cf. https://github.com/ryanoasis/nerd-fonts/pull/356

**Comment by vitorgalvao** [comment]
No need to use `svn`, you can download the `master` zip.

But a better solution is to ask upstream to cut a new release. We prefer that to workarounds.

**Comment by julienma** [comment]
Thanks for the reply. 

I’ll ask for a new release, but I’m not confident: current milestone is past due 2 years, and considering there are dozens more fonts in this repo, it’d involve a lot more work than cutting a new release just for a single font. 

Re: downloading the master zip, would that be better than selectively downloading files via svn? There are dozens of fonts in that repo, it seems a waste of bandwidth to download a big zip just to keep a handful of files.

**Comment by parkerbxyz** [comment]
Re: cutting a new release, the commit message here seems to indicate a new release may be imminent: ryanoasis/nerd-fonts@fa69496.

**Comment by ryanoasis** [comment]
[Release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0) has been cut, not sure if this will change what you want to do here, just an FYI

**Comment by vitorgalvao** [comment]
@ryanoasis Thank you.

@julienma It’s fine if you prefer to close this PR and open a new one. Do whatever’s most convenient.

**Comment by julienma** [comment]
Thank you @ryanoasis :)

@vitorgalvao I've updated the cask using `cask-audit`, PR is here: #1944. Closing this one. Thanks!

**Pull request closed without merging**
