### PR TITLE
IBM Plex - Update to 1.2.3 and change to TrueType

### PR DESCRIPTION
**Pull request by barcia**
* The repository recommends use TrueType instead OpenType in MacOS
* Add Devanagari and Thai versions

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-fonts/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> The repository recommends use TrueType instead OpenType in MacOS

Where? I’d rather keep OpenType unless there’s a good reason to use TrueType.

**Comment by barcia** [comment]
In all releases of [Releases • IBM/Plex](https://github.com/IBM/plex/releases) repo put that: _TrueType.zip is recommended for MacOS and Windows_

Really I don't know who is better, I just wanted update this cask, and as I saw that, I also changed it

**Comment by vitorgalvao** [comment]
I’d rather keep OpenType than blindly following the suggestion. This cask has been in place for a good while without complaints. If there’s a document explaining the reasoning, we’ll consider the change.

If you want to change this (or make a new PR) to keep OpenType but add the * Devanagari and Thai versions, we’ll accept it.

**Comment by barcia** [comment]
Yes, of course, my main intention was just to update the Cask.
Thanks 😉

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
