### PR TITLE
Update `import_google_fonts` to use Git downloads.

### PR DESCRIPTION
**Pull request by reitermarkus**
Addresses https://github.com/Homebrew/homebrew-cask-fonts/pull/6572#issuecomment-130472451.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Opened https://github.com/google/fonts/pull/5518 and https://github.com/google/fonts/pull/5516 to fix some issues.

**Comment by reitermarkus** [comment]
Should be good to go now.

**Review by bevanjkay — APPROVED** [review]

**Comment by p-linnane** [comment]
Thank you for all the work on this @reitermarkus!

**Pull request merged**
