### PR TITLE
font-meslo-for-powerlevel10k: use official source

### PR DESCRIPTION
**Pull request by bevanjkay**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

----

Continuation of #8988 to use the official source.
The downside here is that it won't detect when there is an update (but will replace local files with upstream, if `brew upgrade --greedy` is ran), and the whole git repository has to be checked out due to the files not being located within a subfolder.

CC: @romkatv

### CODE REVIEW

**Comment by romkatv** [comment]
> The downside here is that it won't detect when there is an update (but will replace local files with upstream, if `brew upgrade --greedy` is ran), and the whole git repository has to be checked out due to the files not being located within a subfolder.

What is the right way to set it up without the downsides you mentioned? If I create another repo just for the font files, would that help?

**Comment by bevanjkay** [comment]
@romkatv The best way to be able to notify users when a new update is available for the font would be a repo that has a new release (and therefore also archive) on each update. Then the caskfile could contain a version. 

If this is too difficult having the files in their own repo would be less download overhead, or even keeping them in the same repo but in a subfolder would save some bandwidth.

**Comment by romkatv** [comment]
How about this? https://github.com/romkatv/powerlevel10k-media/releases/tag/v2.3.3

**Comment by p-linnane** [comment]
Thanks for the help here @romkatv! This should be all we need.

**Review by p-linnane — APPROVED** [review]

**Comment by romkatv** [comment]
Thanks a bunch!

**Pull request merged**
