### PR TITLE
Lora: Use upstream repository

### PR DESCRIPTION
**Pull request by adunning**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-fonts/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we just got [a script to keep all Google Fonts updated](https://github.com/Homebrew/homebrew-cask-fonts/pull/2098), so for the moment it’s a better idea to keep those when they exist than to fragment to different repos.

**Comment by adunning** [comment]
`CONTRIBUTING.md` encourages users to switch to upstream repositories where available – does that no longer apply? If we're using unversioned sources instead, how would Homebrew know to update an installed font?

**Comment by vitorgalvao** [comment]
> `CONTRIBUTING.md` encourages users to switch to upstream repositories where available – does that no longer apply?

It’s been a long time since we’ve made that rule. In general I think it’s a good one, but with the addition of the script I also think we should change it.

In truth, this repo requires more maintenance than it’s worth. Most fonts have too few users, but unlike other repos, removing them for low usage seems less warranted. That leads to broken font casks over time, which despite being broken for months or years are only noticed occasionally by users.

Having an automated way to ensure those casks are always working is a huge boon to maintainability. I don’t really like that we’re relying on Google for it ([I wonder when they’ll get tired of it](https://killedbygoogle.com/)) but it’s not like we have a big choice—most of those can only be retrieved from Google Fonts. Whatever we do, we’d have to do a lot of reworking on this repo if Google Fonts went away. I’d see that as a boon, even, clean up everything and readd only what people still want.

> If we're using unversioned sources instead, how would Homebrew know to update an installed font?

It wouldn’t, that’s true. But it’s not like most fonts are updated often (or at all) or are problematic if on an older version, or even have a version.

In general, relying more on Google Fonts seems to be the choice that keeps this tap healthier, and it needs that help.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/2113

**Pull request closed without merging**
