### PR TITLE
Add Firge and FirgeNerd fonts

### PR DESCRIPTION
**Pull request by hideo54**
Hello,

I created a new font cask: Firge and FirgeNerd. [Firge](https://github.com/yuru7/Firge/tree/v0.1.0) is a Japanese font for programming use. It's licensed under SIL Open Font License, which allows redistribution. I am not the creator but allowed to submit this pull request.

Contributing template is below. Note that:
* I have read [Naming Font Casks](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#naming-font-casks) document in this repository instead.
* `brew audit --new-cask` did not work successfully. Running the command raised only one problem: `New casks should use a livecheck instead of an appcast.` I ignored this error because I saw almost all casks in this repository use appcast instead of livecheck. Let me know if I should use livecheck.

---
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by hideo54** [comment]
Thank you for the nice fix, @miccal!

Speaking of notability, well, it's sure Firge does not have enough GitHub stars. However, [Firge](https://github.com/yuru7/Firge) is a derivative version of HackGen font by the same creator. [HackGen](https://github.com/yuru7/HackGen) is a more popular font with 928 GitHub stars and is already registered in this repository ([link](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-hackgen.rb)).
I hope you take this fact into account and merge this PR :pray:

**Comment by vitorgalvao** [comment]
Thank you for the PR, but like [when to contribute](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#when-to-contribute) says:

> The preferred way to add a font to this repository is to [submit it to Google Fonts](https://github.com/google/fonts/blob/master/CONTRIBUTING.md). Shortly after its inclusion, a Cask will be automatically generated and updated on this repository.
>
> We accept fonts from other sources **but they must be provably popular**, like [JetBrains Mono](https://github.com/JetBrains/JetBrainsMono) and [iA Fonts](https://github.com/iaolo/iA-Fonts). To build one of those, keep reading.

This is not provably popular. Other casks already in aren’t a good comparison, because they were included before the rule was created. They’ll be removed as/when/if they break.

We need to do this because otherwise this repo becomes untenable. Too many fonts submitted and used by single-digit people. You may wish to consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by hideo54** [comment]
I see. Thank you for kind explanation.

**Comment by vitorgalvao** [comment]
> I see. Thank you for kind explanation.

Thank you for understanding, and for the nice words.

**Pull request closed without merging**
