### PR TITLE
Add font-makinas

### PR DESCRIPTION
**Pull request by tomy0000000**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-fonts/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by reitermarkus** [comment]
Is “4” part of the name?

**Comment by tomy0000000** [comment]
@reitermarkus Likely is, but I'm not sure whether that's a part of name or version. Will do some research in a while.

**Comment by tomy0000000** [comment]
@reitermarkus After some further googling, I found many website shared info about a font name "Makinas Scrap 5" with links point to the page of "Makinas 4". However those post are created date back before those of "Makinas 4". Although it sounds weird, but I believe "Makinas 4" is actually a descendent of "Makinas Scrap 5", and following the guessing, that means the 4 and 5 within the name should not be seen as version number.

All in all, I suggest leave the name as is.

**Comment by reitermarkus** [comment]
If it's not a version number, I think it needs to be part of the name.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
