### PR TITLE
Switch Google fonts from svn to git

### PR DESCRIPTION
**Pull request by hmarr**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

Follow-on PR from #5758 to flip the remaining Google fonts over from svn to git. Do not merge until 1) the success to brew 3.6.7 is released and 2) #5758 gets released a week or two have passed with no complaints from users.

It's a big change, so I haven't run `brew audit` on each cask. I have run `brew style` on each cask and they came out okay:

```
$ ls Casks | sed 's/\.rb//' | xargs brew style
Inspecting 1976 files
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

1976 files inspected, no offenses detected
```

To generate this change I wrote a simple autocorrecting Rubocop rule:

```ruby
module RuboCop
  module Cop
    module CustomCops
      class RewriteSvnToGit < Base
        extend AutoCorrector

        MSG = "Installing a Google font with SVN".freeze

        def on_send(node)
          receiver_node, method_name, *arg_nodes = *node
          return unless method_name == :url

          url = arg_nodes.grep(RuboCop::AST::StrNode)&.first
          opts = arg_nodes.grep(RuboCop::AST::HashNode)&.first
          return unless url && opts

          using_node = opts.pairs.select { |p| p.key.value == :using }.first
          return unless using_node && using_node&.value&.value == :svn
          return unless url.value.start_with?("https://github.com/google/fonts/trunk/")

          path = url.value.delete_prefix("https://github.com/google/fonts/trunk/")

          add_offense(using_node) do |corrector|
            corrector.replace(url, "\"https://github.com/google/fonts.git\"")

            opts_replacement = [
              'verified:  "github.com/google/fonts",',
              'branch:    "main",',
              "only_path: \"#{path}\"",
            ].join("\n      ")
            corrector.replace(opts, opts_replacement)
          end
        end
      end
    end
  end
end
```

Then ran it across all fonts with:

```console
$ rubocop --require ./svn_to_git.rb --only CustomCops/RewriteSvnToGit Casks --autocorrect
```

A couple of points to follow up on:
1. There are still some non-Google fonts that are hosted on GitHub and use svn – I should probably modify my Rubocop rule to handle them too.
2. If we're mass-migrating to git, the cache path will change for people who've already installed these fonts. Will the old caches ever get cleaned up?

### CODE REVIEW

**Comment by hmarr** [comment]
Hmm, we might need to split this in two

image

**Comment by miccal** [comment]
@hmarr please split this into separate PR's, say five separate PR's each of 85 Casks, thanks.

**Comment by hmarr** [comment]
I just spotted https://github.com/Homebrew/homebrew-cask-fonts/pull/6574, which updates the Google fonts script use Git, and the two PRs created based on those updates (https://github.com/Homebrew/homebrew-cask-fonts/pull/6580, and https://github.com/Homebrew/homebrew-cask-fonts/pull/6581). Thanks for updating that @reitermarkus! I wasn't aware that script existed.

I'll wait for those PRs to get merged, then I'll rerun this rubocop rule over the remaining SVN fonts to catch any stragglers, and I'll make sure I split it into chunks of 100 fonts per PR or fewer.

**Comment by reitermarkus** [comment]
@hmarr, all Google Fonts are now updated using the updated script.

**Comment by hmarr** [comment]
Great, thanks @reitermarkus!

**Pull request closed without merging**
