### PR TITLE
Update font-hackgen, font-hackgen-nerd from 2.8.0 to 2.9.0 

### PR DESCRIPTION
**Pull request by 5ouma**
Update version from `2.8.0` by this release, `https://github.com/yuru7/HackGen/releases/tag/v2.9.0`.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by 5ouma** [comment]
@members Could you rerun Actions?
This version changed as an official release so that it should succeed.

**Comment by bevanjkay** [comment]
@5ouma Version `2.8.0` is still marked as the "latest" version in the upstream repository.
https://github.com/yuru7/HackGen/releases/latest

Version `2.9.0` is a pre-release.

**Comment by 5ouma** [comment]
It's probably because of forgetting to make it the latest.
The developer @yuru7 said on Twitter to make it an official release [here](https://twitter.com/tawara_san/status/1656998606694645760).

> Since there seems to be no particular problem (probably), I removed the pre-releases of HackGen, PlemolJP, and UDEV Gothic that incorporate Nerd Fonts v3.0 and upgraded them to regular releases 🍺

**Review by bevanjkay — APPROVED** [review]

**Comment by 5ouma** [comment]
Thanks!!

**Pull request merged**
