### PR TITLE
Create merged cask for Powerline fonts

### LINKED ISSUE #2100: Outdated cask: font-dejavu-sans-mono-for-powerline
I want to install **DejaVu Sans Mono for Powerline**，so I run `brew cask install font-dejavu-sans-mono-for-powerline`, but the font can not be downloaded. It seems like cloning the font is not work. And I found 

> https://github.com/powerline/fonts/trunk/DejaVuSansMono

this page cannot be found.

### PR DESCRIPTION
**Pull request by adunning**
Use official release to replace fetching individual files from the repository. Closes #2100.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-fonts/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I’m not sure we want this. Users shouldn’t be forced to install every Powerline font, but they’re few enough to probably not be a big issue.

@afeld Would it be a lot of work to adapt your script to work on this repo as well (or alternatively, any repo with this structure)? Ideally it’d do either these or the google fonts via an argument, not both at once.

**Comment by afeld** [comment]
Certainly possible; will think a bit on how to make it generic enough. Don't want that to be a blocker here though.

**Comment by LeoPhong** [comment]
I use this Powerline font because of fixing the display problem of vs code terminal. Usually will only use one font.

**Comment by LeoPhong** [comment]
I am sorry for my late reply.
I use this Powerline font because of fixing the display problem of vs code terminal. Usually will only use one font.

**Comment by vitorgalvao** [comment]
Going with the decision of having these all separated.

**Pull request closed without merging**
