### PR TITLE
Revert "Update font-iosevka-ss18 from 7.2.8 to 7.3.0"

### PR DESCRIPTION
**Pull request by bevanjkay**
Reverts Homebrew/homebrew-cask-fonts#4512

### CODE REVIEW

**Comment by carlocab** [comment]
Why?

**Comment by bevanjkay** [comment]
@carlocab The release seems to have been removed upstream.

**Review by carlocab — APPROVED** [review]

**Comment by bevanjkay** [comment]
Thanks @carlocab 😃

**Comment by singularitti** [comment]
> @carlocab The release seems to have been removed upstream.

Really? I can still see them: https://github.com/be5invis/Iosevka/releases/tag/v7.3.0

**Comment by carlocab** [comment]
Are the checksums the same? My understanding is that they pulled it then re-released.

**Comment by singularitti** [comment]
Then I should just do PRs again?

**Comment by carlocab** [comment]
Sure, go ahead.

**Pull request merged**
