### PR TITLE
font-*-nerd-font: update to 2.1.0

### LINKED ISSUE #1992: nerd-font is outdated
All `font-*-nerd-font` and `font-*-nerd-font-mono` need updated, and it added some fonts too. see [releases](https://github.com/ryanoasis/nerd-fonts/releases).

It affects so many cases, I prefer not making PR myself. Hope you would handle them, thanks.

### PR DESCRIPTION
**Pull request by holymonson**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

---

1. all font-*-nerd-font casks update to 2.1.0 .
2. combine mono into regular per  [Multiple Fonts per Cask](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#multiple-fonts-per-cask)
3. rename some casks per [Converting the Canonical Name To a Token](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#converting-the-canonical-name-to-a-token)
4. add some missing fonts.

Fix #1992.

### CODE REVIEW

**Comment by holymonson** [comment]
@vitorgalvao This may need manual intervention, would you take a look?

**Comment by reitermarkus** [comment]
Thanks!

**Comment by vitorgalvao** [comment]
Great job, @holymonson! Thank you.

**Comment by alghanmi** [comment]
Thank you, this is great!

I want to note that upgrading an existing setup that has both `font-inconsolatago-nerd-font` and `font-inconsolatago-nerd-font-mono` installed will cause `brew` upgrades to fail because upgrading `font-inconsolatago-nerd-font` will error with:
```
==> Moving Font 'InconsolataGo Nerd Font Complete.ttf' to '/Users/user.name/Library/Fonts/InconsolataGo Nerd Font
Error: It seems there is already a Font at '/Users/user.name/Library/Fonts/InconsolataGo Bold Nerd Font Complete Mono.ttf'.
```

To resolve this issue, I uninstalled both font casks and installed the `font-inconsolatago-nerd-font` again
```
brew cask uninstall font-inconsolatago-nerd-font font-inconsolatago-nerd-font-mono
```
then
```
brew cask install font-inconsolatago-nerd-font
```

**Pull request merged**
