### PR TITLE
Update font-iosevka from 7.3.3 to 8.0.0

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by bevanjkay** [comment]
Mis-named file has been reported upstream - https://github.com/be5invis/Iosevka/issues/1167

**Comment by be5invis** [comment]
@bevanjkay I suggest you to close **all** PRs about Iosevka v8.0.0 since one file's name is incorrect. I will publish v8.0.1 in the next hours.

**Comment by bevanjkay** [comment]
@be5invis Thank you for the quick response.

**Comment by bevanjkay** [comment]
@singularitti FYI

**Pull request closed without merging**
