### PR TITLE
font-iosevka 28.0.0

### PR DESCRIPTION
**Pull request by singularitti**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by singularitti** [comment]
See https://github.com/be5invis/Iosevka/issues/2029

**Review by miccal — APPROVED** [review]

**Comment by be5invis** [comment]
@singularitti  Make sure that you've tested that upgrading from an old version will properly remove old font files under old names and install the fonts under new name.

**Comment by singularitti** [comment]
@be5invis I think when I upgrade with Homebrew, the old font files were removed before installing new fonts, am I right @miccal? At least I cannot see the old font files on my Mac now.

**Comment by miccal** [comment]
> @be5invis I think when I upgrade it with Homebrew, the old font files were removed first before installing new fonts, am I right @miccal? At least I cannot see the old font files on my Mac now.

Yes that is correct.

**Pull request merged**
