### PR TITLE
Delete font-ubuntu.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Refs https://github.com/Homebrew/homebrew-cask-fonts/issues/2255.

This is already covered by the fonts added automatically by the Google Fonts repos script.

### CODE REVIEW

**Comment by zhangyoufu** [comment]
Google font should not be considered as the official upstream of Ubuntu font family. Google’s repo does not have latest copy of Ubuntu font family.

**Comment by vitorgalvao** [comment]
> Google font should not be considered as the official upstream of Ubuntu font family. Google’s repo does not have latest copy of Ubuntu font family.

Unfortunately, this repo is way more trouble than it’s worth, so we’re trying to cut work to a minimum. everything we can automate, we do, and the Google Fons repo is automatable.

If that means a few fonts have to be a little behind, so be it. If you want to help, the correct solution is to open an issue or make a PR on the Google Fonts repo to fix what’s missing. That way it’s fixed for far more people.

**Comment by zhangyoufu** [comment]
I agree that things should be automated. But I don’t think everything relying on Google’s font repo is the correct way to go. I would stop using cask-fonts if this happens.

**Comment by vitorgalvao** [comment]
> I would stop using cask-fonts if this happens.

That’s your choice. It has no effect on this decision.

**Pull request merged**
