### PR TITLE
Add font-nanum

### PR DESCRIPTION
**Pull request by minacle**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

---

There are some already exist fonts by Google Fonts, but this is from the official and has more fonts than Google Fonts providing.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Could you submit these to the Google Fonts repo instead, if they accept them? That way more people would benefit from them, and it’d be way easier for us to maintain. Right now I’m undecided if we should accept these.

**Comment by minacle** [comment]
> Could you submit these to the Google Fonts repo instead, if they accept them?

I didn't know Google Fonts is an open source. I will try for it. Thanks for information.

**Comment by minacle** [comment]
Now I'm finding out a solution. Please don't close this yet.

**Comment by vitorgalvao** [comment]
The solution is to submit these to the Google Fonts repo, which will add them here automatically, so these PRs are no longer necessary.

We’ve recently [made this new policy explicit](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#when-to-contribute).

**Pull request closed without merging**
