### PR TITLE
Update font-iosevka from 8.0.1 to 8.0.2

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by kristoffergr** [comment]
This update seems to break the cask for me:

```
# brew -v upgrade
==> Casks with 'auto_updates' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 2 outdated packages:
font-iosevka-aile 7.3.3 -> 8.0.2
font-iosevka-ss04 7.3.3 -> 8.0.2
==> Upgrading font-iosevka-aile
==> Downloading https://github.com/be5invis/Iosevka/releases/download/v8.0.2/ttc-iosevka-aile-8.0.2.zip
==> Purging files for version 8.0.2 of Cask font-iosevka-aile
==> Upgrading font-iosevka-ss04
==> Downloading https://github.com/be5invis/Iosevka/releases/download/v8.0.2/ttc-iosevka-ss04-8.0.2.zip
==> Purging files for version 8.0.2 of Cask font-iosevka-ss04
Error: Problems with multiple casks:
font-iosevka-aile: Download failed on Cask 'font-iosevka-aile' with message: undefined method `delete_if' for nil:NilClass
font-iosevka-ss04: Download failed on Cask 'font-iosevka-ss04' with message: undefined method `delete_if' for nil:NilClass
```

**Comment by alebcay** [comment]
Looks similar to recent issues we're having in `homebrew-core`. Might be caused by `brew` change https://github.com/Homebrew/brew/pull/11766.

**Comment by bevanjkay** [comment]
@kristoffergr It looks like an problem in homebrew/Brew - could you please open an issue there to get it tracked?

https://github.com/Homebrew/brew

**Comment by kristoffergr** [comment]
Ah, I will take a look at Homebrew/brew#11766, thank you!

**Comment by kristoffergr** [comment]
That does seem to be the problem, and there is already a fix merged. Thank you both again :)

**Pull request merged**
