### PR TITLE
Add Nanum archaic Hangul fonts

### PR DESCRIPTION
**Pull request by minacle**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

---

These are archaic Hangul fonts which series of Nanum fonts, by Naver and Sandoll Communications.

The official is providing two version of type: TTF for general use, OTF for graphical use.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Descriptions must be in English.

**Comment by minacle** [comment]
How about no description? Is it okay?

**Comment by vitorgalvao** [comment]
> How about no description? Is it okay?

No, because it won’t pass tests. And https://github.com/Homebrew/homebrew-cask-fonts/pull/3441#issuecomment-768003035 also applies here.

**Comment by minacle** [comment]
Now I'm finding out a solution. Please don't close this yet.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/3441#issuecomment-786672761

**Pull request closed without merging**
