### PR TITLE
Remove font-neodunggeunmo{,-code}

### PR DESCRIPTION
**Pull request by Dalgona**
Hello, I am the developer/maintainer of the &ldquo;NeoDunggeunmo Project,&rdquo; owner of the [neodgm](https://github.com/neodgm) GitHub organization and its repositories.

I would like to remove the following casks from this repository, because I will from now on provide these font casks from my own (&ldquo;official&rdquo;) Homebrew tap, `neodgm/homebrew-neodgm` (this repository is not public yet, please read more). I have already talked with the volunteer(@nyeong) who has been maintaining these casks.

- `font-neodunggeunmo`
- `font-neodunggeunmo-code`

There are two main reasons why I'm moving these casks:

- **To provide the latest version of font casks as soon as possible**

  I know I can achieve this by simply submitting these fonts to Google Fonts, but I cannot, because even though they are under the SIL OFL 1.1, I am not able to meet the requirements for Google Fonts submission for reasons. Instead, I could craft my own GitHub Actions workflow to instantly update font casks in my tap, whenever the new versions of my fonts are released.

- **To make NeoDunggeunmo and &ldquo;ALL&rdquo; of its official derivations installable via Homebrew**

  See #2492.

Just a quick question: According to [the official documentation](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#naming), casks must have globally unique names. If the casks are deleted from this repository, can I safely take the names of these casks? This is why I still haven't made the `neodgm/homebrew-neodgm` repository public.

_Adios! I, and the original cask maintainer will miss this home!_

- - -

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by Dalgona** [comment]
> **CI / syntax (macos-11.0) (pull_request)** Failing after 1m — syntax (macos-11.0)
>
> ```
> developer/bin/font_casker:98:3: C: [Correctable] Prefer grep_v to reject with a regexp match.
>   IO.popen(cmd, "r", &:read) ...
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> 1751 files inspected, 1 offense detected, 1 offense auto-correctable
> Error: Prefer `grep_v` to `reject` with a regexp match.
> Error: Process completed with exit code 1.
> ```

This is not my fault... I guess... Is it?

**Comment by miccal** [comment]
> > **CI / syntax (macos-11.0) (pull_request)** Failing after 1m — syntax (macos-11.0)
> > ```
> > developer/bin/font_casker:98:3: C: [Correctable] Prefer grep_v to reject with a regexp match.
> >   IO.popen(cmd, "r", &:read) ...
> >   ^^^^^^^^^^^^^^^^^^^^^^^^^^
> > 
> > 1751 files inspected, 1 offense detected, 1 offense auto-correctable
> > Error: Prefer `grep_v` to `reject` with a regexp match.
> > Error: Process completed with exit code 1.
> > ```
> 
> This is not my fault... I guess... Is it?

Fixed in https://github.com/Homebrew/homebrew-cask-fonts/pull/4965

**Comment by vitorgalvao** [comment]
> I could craft my own GitHub Actions workflow to instantly update font casks in my tap, whenever the new versions of my fonts are released.

You could also craft your own GitHub Actions workflow to instantly send the update to us.

But I understand your full reasoning. We’ll merge this when the build passes.

For your own reference, here are the statistics of these:

```
font-neodunggeunmo-code
30 days: 1 (#5459)
90 days: 5 (#4998)
365 days: 41 (#4075)
Age: 714 days (added 2019, October 18)

font-neodunggeunmo
30 days: 3 (#4047)
90 days: 5 (#4997)
365 days: 40 (#4139)
Age: 714 days (added 2019, October 18)
```

**Pull request merged**
